# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quizfinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 4095)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(
            QtCore.QRect(0, 0, 993, 4055))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.questionlabel1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel1.setFont(font)
        self.questionlabel1.setObjectName("questionlabel1")
        self.verticalLayout_2.addWidget(self.questionlabel1)
        self.strongly_agree = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree.setFont(font)
        self.strongly_agree.setObjectName("strongly_agree")
        self.questiongrp1 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp1.setObjectName("questiongrp1")
        self.questiongrp1.addButton(self.strongly_agree)
        self.verticalLayout_2.addWidget(self.strongly_agree)
        self.Agree_1 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_1.setFont(font)
        self.Agree_1.setObjectName("Agree_1")
        self.questiongrp1.addButton(self.Agree_1)
        self.verticalLayout_2.addWidget(self.Agree_1)
        self.Disagree = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree.setFont(font)
        self.Disagree.setObjectName("Disagree")
        self.questiongrp1.addButton(self.Disagree)
        self.verticalLayout_2.addWidget(self.Disagree)
        self.Strongly_Disagree = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree.setFont(font)
        self.Strongly_Disagree.setObjectName("Strongly_Disagree")
        self.questiongrp1.addButton(self.Strongly_Disagree)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree)
        self.questionlabel2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel2.setFont(font)
        self.questionlabel2.setObjectName("questionlabel2")
        self.verticalLayout_2.addWidget(self.questionlabel2)
        self.strongly_agree_2 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_2.setFont(font)
        self.strongly_agree_2.setObjectName("strongly_agree_2")
        self.questiongrp2 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp2.setObjectName("questiongrp2")
        self.questiongrp2.addButton(self.strongly_agree_2)
        self.verticalLayout_2.addWidget(self.strongly_agree_2)
        self.Agree_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_2.setFont(font)
        self.Agree_2.setObjectName("Agree_2")
        self.questiongrp2.addButton(self.Agree_2)
        self.verticalLayout_2.addWidget(self.Agree_2)
        self.Disagree_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_2.setFont(font)
        self.Disagree_2.setObjectName("Disagree_2")
        self.questiongrp2.addButton(self.Disagree_2)
        self.verticalLayout_2.addWidget(self.Disagree_2)
        self.Strongly_Disagree_2 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_2.setFont(font)
        self.Strongly_Disagree_2.setObjectName("Strongly_Disagree_2")
        self.questiongrp2.addButton(self.Strongly_Disagree_2)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_2)
        self.questionlabel3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel3.setFont(font)
        self.questionlabel3.setObjectName("questionlabel3")
        self.verticalLayout_2.addWidget(self.questionlabel3)
        self.strongly_agree_3 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_3.setFont(font)
        self.strongly_agree_3.setObjectName("strongly_agree_3")
        self.questiongrp3 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp3.setObjectName("questiongrp3")
        self.questiongrp3.addButton(self.strongly_agree_3)
        self.verticalLayout_2.addWidget(self.strongly_agree_3)
        self.Agree_3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_3.setFont(font)
        self.Agree_3.setObjectName("Agree_3")
        self.questiongrp3.addButton(self.Agree_3)
        self.verticalLayout_2.addWidget(self.Agree_3)
        self.Disagree_3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_3.setFont(font)
        self.Disagree_3.setObjectName("Disagree_3")
        self.questiongrp3.addButton(self.Disagree_3)
        self.verticalLayout_2.addWidget(self.Disagree_3)
        self.Strongly_Disagree_3 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_3.setFont(font)
        self.Strongly_Disagree_3.setObjectName("Strongly_Disagree_3")
        self.questiongrp3.addButton(self.Strongly_Disagree_3)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_3)
        self.questionlabel4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel4.setFont(font)
        self.questionlabel4.setObjectName("questionlabel4")
        self.verticalLayout_2.addWidget(self.questionlabel4)
        self.strongly_agree_4 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_4.setFont(font)
        self.strongly_agree_4.setObjectName("strongly_agree_4")
        self.questiongrp4 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp4.setObjectName("questiongrp4")
        self.questiongrp4.addButton(self.strongly_agree_4)
        self.verticalLayout_2.addWidget(self.strongly_agree_4)
        self.Agree_4 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_4.setFont(font)
        self.Agree_4.setObjectName("Agree_4")
        self.questiongrp4.addButton(self.Agree_4)
        self.verticalLayout_2.addWidget(self.Agree_4)
        self.Disagree_4 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_4.setFont(font)
        self.Disagree_4.setObjectName("Disagree_4")
        self.questiongrp4.addButton(self.Disagree_4)
        self.verticalLayout_2.addWidget(self.Disagree_4)
        self.Strongly_Disagree_4 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_4.setFont(font)
        self.Strongly_Disagree_4.setObjectName("Strongly_Disagree_4")
        self.questiongrp4.addButton(self.Strongly_Disagree_4)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_4)
        self.questionlabel5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel5.setFont(font)
        self.questionlabel5.setObjectName("questionlabel5")
        self.verticalLayout_2.addWidget(self.questionlabel5)
        self.strongly_agree_5 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_5.setFont(font)
        self.strongly_agree_5.setObjectName("strongly_agree_5")
        self.questiongrp5 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp5.setObjectName("questiongrp5")
        self.questiongrp5.addButton(self.strongly_agree_5)
        self.verticalLayout_2.addWidget(self.strongly_agree_5)
        self.Agree_5 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_5.setFont(font)
        self.Agree_5.setObjectName("Agree_5")
        self.questiongrp5.addButton(self.Agree_5)
        self.verticalLayout_2.addWidget(self.Agree_5)
        self.Disagree_5 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_5.setFont(font)
        self.Disagree_5.setObjectName("Disagree_5")
        self.questiongrp5.addButton(self.Disagree_5)
        self.verticalLayout_2.addWidget(self.Disagree_5)
        self.Strongly_Disagree_5 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_5.setFont(font)
        self.Strongly_Disagree_5.setObjectName("Strongly_Disagree_5")
        self.questiongrp5.addButton(self.Strongly_Disagree_5)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_5)
        self.questionlabel6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel6.setFont(font)
        self.questionlabel6.setObjectName("questionlabel6")
        self.verticalLayout_2.addWidget(self.questionlabel6)
        self.strongly_agree_6 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_6.setFont(font)
        self.strongly_agree_6.setObjectName("strongly_agree_6")
        self.questiongrp6 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp6.setObjectName("questiongrp6")
        self.questiongrp6.addButton(self.strongly_agree_6)
        self.verticalLayout_2.addWidget(self.strongly_agree_6)
        self.Agree_6 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_6.setFont(font)
        self.Agree_6.setObjectName("Agree_6")
        self.questiongrp6.addButton(self.Agree_6)
        self.verticalLayout_2.addWidget(self.Agree_6)
        self.Disagree_6 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_6.setFont(font)
        self.Disagree_6.setObjectName("Disagree_6")
        self.questiongrp6.addButton(self.Disagree_6)
        self.verticalLayout_2.addWidget(self.Disagree_6)
        self.Strongly_Disagree_6 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_6.setFont(font)
        self.Strongly_Disagree_6.setObjectName("Strongly_Disagree_6")
        self.questiongrp6.addButton(self.Strongly_Disagree_6)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_6)
        self.questionlabel7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel7.setFont(font)
        self.questionlabel7.setObjectName("questionlabel7")
        self.verticalLayout_2.addWidget(self.questionlabel7)
        self.strongly_agree_7 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_7.setFont(font)
        self.strongly_agree_7.setObjectName("strongly_agree_7")
        self.questiongrp7 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp7.setObjectName("questiongrp7")
        self.questiongrp7.addButton(self.strongly_agree_7)
        self.verticalLayout_2.addWidget(self.strongly_agree_7)
        self.Agree_7 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_7.setFont(font)
        self.Agree_7.setObjectName("Agree_7")
        self.questiongrp7.addButton(self.Agree_7)
        self.verticalLayout_2.addWidget(self.Agree_7)
        self.Disagree_7 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_7.setFont(font)
        self.Disagree_7.setObjectName("Disagree_7")
        self.questiongrp7.addButton(self.Disagree_7)
        self.verticalLayout_2.addWidget(self.Disagree_7)
        self.Strongly_Disagree_7 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_7.setFont(font)
        self.Strongly_Disagree_7.setObjectName("Strongly_Disagree_7")
        self.questiongrp7.addButton(self.Strongly_Disagree_7)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_7)
        self.questionlabel8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel8.setFont(font)
        self.questionlabel8.setObjectName("questionlabel8")
        self.verticalLayout_2.addWidget(self.questionlabel8)
        self.strongly_agree_8 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_8.setFont(font)
        self.strongly_agree_8.setObjectName("strongly_agree_8")
        self.questiongrp8 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp8.setObjectName("questiongrp8")
        self.questiongrp8.addButton(self.strongly_agree_8)
        self.verticalLayout_2.addWidget(self.strongly_agree_8)
        self.Agree_8 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_8.setFont(font)
        self.Agree_8.setObjectName("Agree_8")
        self.questiongrp8.addButton(self.Agree_8)
        self.verticalLayout_2.addWidget(self.Agree_8)
        self.Disagree_8 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_8.setFont(font)
        self.Disagree_8.setObjectName("Disagree_8")
        self.questiongrp8.addButton(self.Disagree_8)
        self.verticalLayout_2.addWidget(self.Disagree_8)
        self.Strongly_Disagree_8 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_8.setFont(font)
        self.Strongly_Disagree_8.setObjectName("Strongly_Disagree_8")
        self.questiongrp8.addButton(self.Strongly_Disagree_8)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_8)
        self.questionlabel9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel9.setFont(font)
        self.questionlabel9.setObjectName("questionlabel9")
        self.verticalLayout_2.addWidget(self.questionlabel9)
        self.strongly_agree_9 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_9.setFont(font)
        self.strongly_agree_9.setObjectName("strongly_agree_9")
        self.questiongrp9 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp9.setObjectName("questiongrp9")
        self.questiongrp9.addButton(self.strongly_agree_9)
        self.verticalLayout_2.addWidget(self.strongly_agree_9)
        self.Agree_9 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_9.setFont(font)
        self.Agree_9.setObjectName("Agree_9")
        self.questiongrp9.addButton(self.Agree_9)
        self.verticalLayout_2.addWidget(self.Agree_9)
        self.Disagree_9 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_9.setFont(font)
        self.Disagree_9.setObjectName("Disagree_9")
        self.questiongrp9.addButton(self.Disagree_9)
        self.verticalLayout_2.addWidget(self.Disagree_9)
        self.Strongly_Disagree_9 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_9.setFont(font)
        self.Strongly_Disagree_9.setObjectName("Strongly_Disagree_9")
        self.questiongrp9.addButton(self.Strongly_Disagree_9)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_9)
        self.questionlabel10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel10.setFont(font)
        self.questionlabel10.setObjectName("questionlabel10")
        self.verticalLayout_2.addWidget(self.questionlabel10)
        self.strongly_agree_10 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_10.setFont(font)
        self.strongly_agree_10.setObjectName("strongly_agree_10")
        self.questiongrp10 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp10.setObjectName("questiongrp10")
        self.questiongrp10.addButton(self.strongly_agree_10)
        self.verticalLayout_2.addWidget(self.strongly_agree_10)
        self.Agree_10 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_10.setFont(font)
        self.Agree_10.setObjectName("Agree_10")
        self.questiongrp10.addButton(self.Agree_10)
        self.verticalLayout_2.addWidget(self.Agree_10)
        self.Disagree_10 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_10.setFont(font)
        self.Disagree_10.setObjectName("Disagree_10")
        self.questiongrp10.addButton(self.Disagree_10)
        self.verticalLayout_2.addWidget(self.Disagree_10)
        self.Strongly_Disagree_10 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_10.setFont(font)
        self.Strongly_Disagree_10.setObjectName("Strongly_Disagree_10")
        self.questiongrp10.addButton(self.Strongly_Disagree_10)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_10)
        self.questionlabel11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel11.setFont(font)
        self.questionlabel11.setObjectName("questionlabel11")
        self.verticalLayout_2.addWidget(self.questionlabel11)
        self.strongly_agree_11 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_11.setFont(font)
        self.strongly_agree_11.setObjectName("strongly_agree_11")
        self.questiongrp11 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp11.setObjectName("questiongrp11")
        self.questiongrp11.addButton(self.strongly_agree_11)
        self.verticalLayout_2.addWidget(self.strongly_agree_11)
        self.Agree_11 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_11.setFont(font)
        self.Agree_11.setObjectName("Agree_11")
        self.questiongrp11.addButton(self.Agree_11)
        self.verticalLayout_2.addWidget(self.Agree_11)
        self.Disagree_11 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_11.setFont(font)
        self.Disagree_11.setObjectName("Disagree_11")
        self.questiongrp11.addButton(self.Disagree_11)
        self.verticalLayout_2.addWidget(self.Disagree_11)
        self.Strongly_Disagree_11 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_11.setFont(font)
        self.Strongly_Disagree_11.setObjectName("Strongly_Disagree_11")
        self.questiongrp11.addButton(self.Strongly_Disagree_11)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_11)
        self.questionlabel12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel12.setFont(font)
        self.questionlabel12.setObjectName("questionlabel12")
        self.verticalLayout_2.addWidget(self.questionlabel12)
        self.strongly_agree_12 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_12.setFont(font)
        self.strongly_agree_12.setObjectName("strongly_agree_12")
        self.questiongrp12 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp12.setObjectName("questiongrp12")
        self.questiongrp12.addButton(self.strongly_agree_12)
        self.verticalLayout_2.addWidget(self.strongly_agree_12)
        self.Agree_12 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_12.setFont(font)
        self.Agree_12.setObjectName("Agree_12")
        self.questiongrp12.addButton(self.Agree_12)
        self.verticalLayout_2.addWidget(self.Agree_12)
        self.Disagree_12 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_12.setFont(font)
        self.Disagree_12.setObjectName("Disagree_12")
        self.questiongrp12.addButton(self.Disagree_12)
        self.verticalLayout_2.addWidget(self.Disagree_12)
        self.Strongly_Disagree_12 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_12.setFont(font)
        self.Strongly_Disagree_12.setObjectName("Strongly_Disagree_12")
        self.questiongrp12.addButton(self.Strongly_Disagree_12)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_12)
        self.questionlabel13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel13.setFont(font)
        self.questionlabel13.setObjectName("questionlabel13")
        self.verticalLayout_2.addWidget(self.questionlabel13)
        self.strongly_agree_13 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_13.setFont(font)
        self.strongly_agree_13.setObjectName("strongly_agree_13")
        self.questiongrp13 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp13.setObjectName("questiongrp13")
        self.questiongrp13.addButton(self.strongly_agree_13)
        self.verticalLayout_2.addWidget(self.strongly_agree_13)
        self.Agree_13 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_13.setFont(font)
        self.Agree_13.setObjectName("Agree_13")
        self.questiongrp13.addButton(self.Agree_13)
        self.verticalLayout_2.addWidget(self.Agree_13)
        self.Disagree_13 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_13.setFont(font)
        self.Disagree_13.setObjectName("Disagree_13")
        self.questiongrp13.addButton(self.Disagree_13)
        self.verticalLayout_2.addWidget(self.Disagree_13)
        self.Strongly_Disagree_13 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_13.setFont(font)
        self.Strongly_Disagree_13.setObjectName("Strongly_Disagree_13")
        self.questiongrp13.addButton(self.Strongly_Disagree_13)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_13)
        self.questionlabel14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel14.setFont(font)
        self.questionlabel14.setObjectName("questionlabel14")
        self.verticalLayout_2.addWidget(self.questionlabel14)
        self.strongly_agree_14 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_14.setFont(font)
        self.strongly_agree_14.setObjectName("strongly_agree_14")
        self.questiongrp14 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp14.setObjectName("questiongrp14")
        self.questiongrp14.addButton(self.strongly_agree_14)
        self.verticalLayout_2.addWidget(self.strongly_agree_14)
        self.Agree_14 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_14.setFont(font)
        self.Agree_14.setObjectName("Agree_14")
        self.questiongrp14.addButton(self.Agree_14)
        self.verticalLayout_2.addWidget(self.Agree_14)
        self.Disagree_14 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_14.setFont(font)
        self.Disagree_14.setObjectName("Disagree_14")
        self.questiongrp14.addButton(self.Disagree_14)
        self.verticalLayout_2.addWidget(self.Disagree_14)
        self.Strongly_Disagree_14 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_14.setFont(font)
        self.Strongly_Disagree_14.setObjectName("Strongly_Disagree_14")
        self.questiongrp14.addButton(self.Strongly_Disagree_14)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_14)
        self.questionlabel15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel15.setFont(font)
        self.questionlabel15.setObjectName("questionlabel15")
        self.verticalLayout_2.addWidget(self.questionlabel15)
        self.strongly_agree_15 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_15.setFont(font)
        self.strongly_agree_15.setObjectName("strongly_agree_15")
        self.questiongrp15 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp15.setObjectName("questiongrp15")
        self.questiongrp15.addButton(self.strongly_agree_15)
        self.verticalLayout_2.addWidget(self.strongly_agree_15)
        self.Agree_15 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_15.setFont(font)
        self.Agree_15.setObjectName("Agree_15")
        self.questiongrp15.addButton(self.Agree_15)
        self.verticalLayout_2.addWidget(self.Agree_15)
        self.Disagree_15 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_15.setFont(font)
        self.Disagree_15.setObjectName("Disagree_15")
        self.questiongrp15.addButton(self.Disagree_15)
        self.verticalLayout_2.addWidget(self.Disagree_15)
        self.Strongly_Disagree_15 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_15.setFont(font)
        self.Strongly_Disagree_15.setObjectName("Strongly_Disagree_15")
        self.questiongrp15.addButton(self.Strongly_Disagree_15)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_15)
        self.questionlabel16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel16.setFont(font)
        self.questionlabel16.setObjectName("questionlabel16")
        self.verticalLayout_2.addWidget(self.questionlabel16)
        self.strongly_agree_16 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_16.setFont(font)
        self.strongly_agree_16.setObjectName("strongly_agree_16")
        self.questiongrp16 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp16.setObjectName("questiongrp16")
        self.questiongrp16.addButton(self.strongly_agree_16)
        self.verticalLayout_2.addWidget(self.strongly_agree_16)
        self.Agree_16 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_16.setFont(font)
        self.Agree_16.setObjectName("Agree_16")
        self.questiongrp16.addButton(self.Agree_16)
        self.verticalLayout_2.addWidget(self.Agree_16)
        self.Disagree_16 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_16.setFont(font)
        self.Disagree_16.setObjectName("Disagree_16")
        self.questiongrp16.addButton(self.Disagree_16)
        self.verticalLayout_2.addWidget(self.Disagree_16)
        self.Strongly_Disagree_16 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_16.setFont(font)
        self.Strongly_Disagree_16.setObjectName("Strongly_Disagree_16")
        self.questiongrp16.addButton(self.Strongly_Disagree_16)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_16)
        self.questionlabel17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel17.setFont(font)
        self.questionlabel17.setObjectName("questionlabel17")
        self.verticalLayout_2.addWidget(self.questionlabel17)
        self.strongly_agree_17 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_17.setFont(font)
        self.strongly_agree_17.setObjectName("strongly_agree_17")
        self.questiongrp17 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp17.setObjectName("questiongrp17")
        self.questiongrp17.addButton(self.strongly_agree_17)
        self.verticalLayout_2.addWidget(self.strongly_agree_17)
        self.Agree_17 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_17.setFont(font)
        self.Agree_17.setObjectName("Agree_17")
        self.questiongrp17.addButton(self.Agree_17)
        self.verticalLayout_2.addWidget(self.Agree_17)
        self.Disagree_17 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_17.setFont(font)
        self.Disagree_17.setObjectName("Disagree_17")
        self.questiongrp17.addButton(self.Disagree_17)
        self.verticalLayout_2.addWidget(self.Disagree_17)
        self.Strongly_Disagree_17 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_17.setFont(font)
        self.Strongly_Disagree_17.setObjectName("Strongly_Disagree_17")
        self.questiongrp17.addButton(self.Strongly_Disagree_17)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_17)
        self.questionlabel18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel18.setFont(font)
        self.questionlabel18.setObjectName("questionlabel18")
        self.verticalLayout_2.addWidget(self.questionlabel18)
        self.strongly_agree_18 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_18.setFont(font)
        self.strongly_agree_18.setObjectName("strongly_agree_18")
        self.questiongrp18 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp18.setObjectName("questiongrp18")
        self.questiongrp18.addButton(self.strongly_agree_18)
        self.verticalLayout_2.addWidget(self.strongly_agree_18)
        self.Agree_18 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_18.setFont(font)
        self.Agree_18.setObjectName("Agree_18")
        self.questiongrp18.addButton(self.Agree_18)
        self.verticalLayout_2.addWidget(self.Agree_18)
        self.Disagree_18 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_18.setFont(font)
        self.Disagree_18.setObjectName("Disagree_18")
        self.questiongrp18.addButton(self.Disagree_18)
        self.verticalLayout_2.addWidget(self.Disagree_18)
        self.Strongly_Disagree_18 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_18.setFont(font)
        self.Strongly_Disagree_18.setObjectName("Strongly_Disagree_18")
        self.questiongrp18.addButton(self.Strongly_Disagree_18)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_18)
        self.questionlabel19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel19.setFont(font)
        self.questionlabel19.setObjectName("questionlabel19")
        self.verticalLayout_2.addWidget(self.questionlabel19)
        self.strongly_agree_19 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_19.setFont(font)
        self.strongly_agree_19.setObjectName("strongly_agree_19")
        self.questiongrp19 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp19.setObjectName("questiongrp19")
        self.questiongrp19.addButton(self.strongly_agree_19)
        self.verticalLayout_2.addWidget(self.strongly_agree_19)
        self.Agree_19 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_19.setFont(font)
        self.Agree_19.setObjectName("Agree_19")
        self.questiongrp19.addButton(self.Agree_19)
        self.verticalLayout_2.addWidget(self.Agree_19)
        self.Disagree_19 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_19.setFont(font)
        self.Disagree_19.setObjectName("Disagree_19")
        self.questiongrp19.addButton(self.Disagree_19)
        self.verticalLayout_2.addWidget(self.Disagree_19)
        self.Strongly_Disagree_19 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_19.setFont(font)
        self.Strongly_Disagree_19.setObjectName("Strongly_Disagree_19")
        self.questiongrp19.addButton(self.Strongly_Disagree_19)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_19)
        self.questionlabel20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.questionlabel20.setFont(font)
        self.questionlabel20.setObjectName("questionlabel20")
        self.verticalLayout_2.addWidget(self.questionlabel20)
        self.strongly_agree_20 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.strongly_agree_20.setFont(font)
        self.strongly_agree_20.setObjectName("strongly_agree_20")
        self.questiongrp20 = QtWidgets.QButtonGroup(MainWindow)
        self.questiongrp20.setObjectName("questiongrp20")
        self.questiongrp20.addButton(self.strongly_agree_20)
        self.verticalLayout_2.addWidget(self.strongly_agree_20)
        self.Agree_20 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Agree_20.setFont(font)
        self.Agree_20.setObjectName("Agree_20")
        self.questiongrp20.addButton(self.Agree_20)
        self.verticalLayout_2.addWidget(self.Agree_20)
        self.Disagree_20 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Disagree_20.setFont(font)
        self.Disagree_20.setObjectName("Disagree_20")
        self.questiongrp20.addButton(self.Disagree_20)
        self.verticalLayout_2.addWidget(self.Disagree_20)
        self.Strongly_Disagree_20 = QtWidgets.QRadioButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Strongly_Disagree_20.setFont(font)
        self.Strongly_Disagree_20.setObjectName("Strongly_Disagree_20")
        self.questiongrp20.addButton(self.Strongly_Disagree_20)
        self.verticalLayout_2.addWidget(self.Strongly_Disagree_20)
        self.t1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.t1.setObjectName("t1")
        self.verticalLayout_2.addWidget(self.t1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.Agree_1.toggled.connect(self.checkstate)
        self.strongly_agree.toggled.connect(self.checkstate)
        self.Disagree.toggled.connect(self.checkstate)
        self.Strongly_Disagree.toggled.connect(self.checkstate)

        self.Agree_2.toggled.connect(self.checkstate)
        self.strongly_agree_2.toggled.connect(self.checkstate)
        self.Disagree_2.toggled.connect(self.checkstate)
        self.Strongly_Disagree_2.toggled.connect(self.checkstate)

        self.Agree_3.toggled.connect(self.checkstate)
        self.strongly_agree_3.toggled.connect(self.checkstate)
        self.Disagree_3.toggled.connect(self.checkstate)
        self.Strongly_Disagree_3.toggled.connect(self.checkstate)

        self.Agree_4.toggled.connect(self.checkstate)
        self.strongly_agree_4.toggled.connect(self.checkstate)
        self.Disagree_4.toggled.connect(self.checkstate)
        self.Strongly_Disagree_4.toggled.connect(self.checkstate)

        self.Agree_5.toggled.connect(self.checkstate)
        self.strongly_agree_5.toggled.connect(self.checkstate)
        self.Disagree_5.toggled.connect(self.checkstate)
        self.Strongly_Disagree_5.toggled.connect(self.checkstate)

        self.Agree_6.toggled.connect(self.checkstate)
        self.strongly_agree_6.toggled.connect(self.checkstate)
        self.Disagree_6.toggled.connect(self.checkstate)
        self.Strongly_Disagree_6.toggled.connect(self.checkstate)

        self.Agree_7.toggled.connect(self.checkstate)
        self.strongly_agree_7.toggled.connect(self.checkstate)
        self.Disagree_7.toggled.connect(self.checkstate)
        self.Strongly_Disagree_7.toggled.connect(self.checkstate)

        self.Agree_8.toggled.connect(self.checkstate)
        self.strongly_agree_8.toggled.connect(self.checkstate)
        self.Disagree_8.toggled.connect(self.checkstate)
        self.Strongly_Disagree_8.toggled.connect(self.checkstate)

        self.Agree_9.toggled.connect(self.checkstate)
        self.strongly_agree_9.toggled.connect(self.checkstate)
        self.Disagree_9.toggled.connect(self.checkstate)
        self.Strongly_Disagree_9.toggled.connect(self.checkstate)

        self.Agree_10.toggled.connect(self.checkstate)
        self.strongly_agree_10.toggled.connect(self.checkstate)
        self.Disagree_10.toggled.connect(self.checkstate)
        self.Strongly_Disagree_10.toggled.connect(self.checkstate)

        self.Agree_11.toggled.connect(self.checkstate)
        self.strongly_agree_11.toggled.connect(self.checkstate)
        self.Disagree_11.toggled.connect(self.checkstate)
        self.Strongly_Disagree_11.toggled.connect(self.checkstate)

        self.Agree_12.toggled.connect(self.checkstate)
        self.strongly_agree_12.toggled.connect(self.checkstate)
        self.Disagree_12.toggled.connect(self.checkstate)
        self.Strongly_Disagree_12.toggled.connect(self.checkstate)

        self.Agree_13.toggled.connect(self.checkstate)
        self.strongly_agree_13.toggled.connect(self.checkstate)
        self.Disagree_13.toggled.connect(self.checkstate)
        self.Strongly_Disagree_13.toggled.connect(self.checkstate)

        self.Agree_14.toggled.connect(self.checkstate)
        self.strongly_agree_14.toggled.connect(self.checkstate)
        self.Disagree_14.toggled.connect(self.checkstate)
        self.Strongly_Disagree_14.toggled.connect(self.checkstate)

        self.Agree_15.toggled.connect(self.checkstate)
        self.strongly_agree_15.toggled.connect(self.checkstate)
        self.Disagree_15.toggled.connect(self.checkstate)
        self.Strongly_Disagree_15.toggled.connect(self.checkstate)

        self.Agree_16.toggled.connect(self.checkstate)
        self.strongly_agree_16.toggled.connect(self.checkstate)
        self.Disagree_16.toggled.connect(self.checkstate)
        self.Strongly_Disagree_16.toggled.connect(self.checkstate)

        self.Agree_17.toggled.connect(self.checkstate)
        self.strongly_agree_17.toggled.connect(self.checkstate)
        self.Disagree_17.toggled.connect(self.checkstate)
        self.Strongly_Disagree_17.toggled.connect(self.checkstate)

        self.Agree_18.toggled.connect(self.checkstate)
        self.strongly_agree_18.toggled.connect(self.checkstate)
        self.Disagree_18.toggled.connect(self.checkstate)
        self.Strongly_Disagree_18.toggled.connect(self.checkstate)

        self.Agree_19.toggled.connect(self.checkstate)
        self.strongly_agree_19.toggled.connect(self.checkstate)
        self.Disagree_19.toggled.connect(self.checkstate)
        self.Strongly_Disagree_19.toggled.connect(self.checkstate)

        self.Agree_20.toggled.connect(self.checkstate)
        self.strongly_agree_20.toggled.connect(self.checkstate)
        self.Disagree_20.toggled.connect(self.checkstate)
        self.Strongly_Disagree_20.toggled.connect(self.checkstate)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.strongly_agree, self.Agree_1)
        MainWindow.setTabOrder(self.Agree_1, self.Disagree)
        MainWindow.setTabOrder(self.Disagree, self.Strongly_Disagree)
        MainWindow.setTabOrder(self.Strongly_Disagree, self.strongly_agree_2)
        MainWindow.setTabOrder(self.strongly_agree_2, self.Agree_2)
        MainWindow.setTabOrder(self.Agree_2, self.Disagree_2)
        MainWindow.setTabOrder(self.Disagree_2, self.Strongly_Disagree_2)
        MainWindow.setTabOrder(self.Strongly_Disagree_2, self.strongly_agree_3)
        MainWindow.setTabOrder(self.strongly_agree_3, self.Agree_3)
        MainWindow.setTabOrder(self.Agree_3, self.Disagree_3)
        MainWindow.setTabOrder(self.Disagree_3, self.Strongly_Disagree_3)
        MainWindow.setTabOrder(self.Strongly_Disagree_3, self.strongly_agree_4)
        MainWindow.setTabOrder(self.strongly_agree_4, self.Agree_4)
        MainWindow.setTabOrder(self.Agree_4, self.Disagree_4)
        MainWindow.setTabOrder(self.Disagree_4, self.Strongly_Disagree_4)
        MainWindow.setTabOrder(self.Strongly_Disagree_4, self.strongly_agree_5)
        MainWindow.setTabOrder(self.strongly_agree_5, self.Agree_5)
        MainWindow.setTabOrder(self.Agree_5, self.Disagree_5)
        MainWindow.setTabOrder(self.Disagree_5, self.Strongly_Disagree_5)
        MainWindow.setTabOrder(self.Strongly_Disagree_5, self.strongly_agree_6)
        MainWindow.setTabOrder(self.strongly_agree_6, self.Agree_6)
        MainWindow.setTabOrder(self.Agree_6, self.Disagree_6)
        MainWindow.setTabOrder(self.Disagree_6, self.Strongly_Disagree_6)
        MainWindow.setTabOrder(self.Strongly_Disagree_6, self.strongly_agree_7)
        MainWindow.setTabOrder(self.strongly_agree_7, self.Agree_7)
        MainWindow.setTabOrder(self.Agree_7, self.Disagree_7)
        MainWindow.setTabOrder(self.Disagree_7, self.Strongly_Disagree_7)
        MainWindow.setTabOrder(self.Strongly_Disagree_7, self.strongly_agree_8)
        MainWindow.setTabOrder(self.strongly_agree_8, self.Agree_8)
        MainWindow.setTabOrder(self.Agree_8, self.Disagree_8)
        MainWindow.setTabOrder(self.Disagree_8, self.Strongly_Disagree_8)
        MainWindow.setTabOrder(self.Strongly_Disagree_8, self.strongly_agree_9)
        MainWindow.setTabOrder(self.strongly_agree_9, self.Agree_9)
        MainWindow.setTabOrder(self.Agree_9, self.Disagree_9)
        MainWindow.setTabOrder(self.Disagree_9, self.Strongly_Disagree_9)
        MainWindow.setTabOrder(self.Strongly_Disagree_9,
                               self.strongly_agree_10)
        MainWindow.setTabOrder(self.strongly_agree_10, self.Agree_10)
        MainWindow.setTabOrder(self.Agree_10, self.Disagree_10)
        MainWindow.setTabOrder(self.Disagree_10, self.Strongly_Disagree_10)
        MainWindow.setTabOrder(self.Strongly_Disagree_10,
                               self.strongly_agree_11)
        MainWindow.setTabOrder(self.strongly_agree_11, self.Agree_11)
        MainWindow.setTabOrder(self.Agree_11, self.Disagree_11)
        MainWindow.setTabOrder(self.Disagree_11, self.Strongly_Disagree_11)
        MainWindow.setTabOrder(self.Strongly_Disagree_11,
                               self.strongly_agree_12)
        MainWindow.setTabOrder(self.strongly_agree_12, self.Agree_12)
        MainWindow.setTabOrder(self.Agree_12, self.Disagree_12)
        MainWindow.setTabOrder(self.Disagree_12, self.Strongly_Disagree_12)
        MainWindow.setTabOrder(self.Strongly_Disagree_12,
                               self.strongly_agree_13)
        MainWindow.setTabOrder(self.strongly_agree_13, self.Agree_13)
        MainWindow.setTabOrder(self.Agree_13, self.Disagree_13)
        MainWindow.setTabOrder(self.Disagree_13, self.Strongly_Disagree_13)
        MainWindow.setTabOrder(self.Strongly_Disagree_13,
                               self.strongly_agree_14)
        MainWindow.setTabOrder(self.strongly_agree_14, self.Agree_14)
        MainWindow.setTabOrder(self.Agree_14, self.Disagree_14)
        MainWindow.setTabOrder(self.Disagree_14, self.Strongly_Disagree_14)
        MainWindow.setTabOrder(self.Strongly_Disagree_14,
                               self.strongly_agree_15)
        MainWindow.setTabOrder(self.strongly_agree_15, self.Agree_15)
        MainWindow.setTabOrder(self.Agree_15, self.Disagree_15)
        MainWindow.setTabOrder(self.Disagree_15, self.Strongly_Disagree_15)
        MainWindow.setTabOrder(self.Strongly_Disagree_15,
                               self.strongly_agree_16)
        MainWindow.setTabOrder(self.strongly_agree_16, self.Agree_16)
        MainWindow.setTabOrder(self.Agree_16, self.Disagree_16)
        MainWindow.setTabOrder(self.Disagree_16, self.Strongly_Disagree_16)
        MainWindow.setTabOrder(self.Strongly_Disagree_16,
                               self.strongly_agree_17)
        MainWindow.setTabOrder(self.strongly_agree_17, self.Agree_17)
        MainWindow.setTabOrder(self.Agree_17, self.Disagree_17)
        MainWindow.setTabOrder(self.Disagree_17, self.Strongly_Disagree_17)
        MainWindow.setTabOrder(self.Strongly_Disagree_17,
                               self.strongly_agree_18)
        MainWindow.setTabOrder(self.strongly_agree_18,
                               self.Strongly_Disagree_19)
        MainWindow.setTabOrder(self.Strongly_Disagree_19, self.Agree_18)
        MainWindow.setTabOrder(self.Agree_18, self.Disagree_19)
        MainWindow.setTabOrder(self.Disagree_19, self.Strongly_Disagree_20)
        MainWindow.setTabOrder(self.Strongly_Disagree_20,
                               self.strongly_agree_20)
        MainWindow.setTabOrder(self.strongly_agree_20, self.Disagree_18)
        MainWindow.setTabOrder(self.Disagree_18, self.Agree_20)
        MainWindow.setTabOrder(self.Agree_20, self.Agree_19)
        MainWindow.setTabOrder(self.Agree_19, self.strongly_agree_19)
        MainWindow.setTabOrder(self.strongly_agree_19, self.Disagree_20)
        MainWindow.setTabOrder(self.Disagree_20, self.Strongly_Disagree_18)

    def checkstate(self):
        state1 = 0
        state2 = 0
        state3 = 0
        state4 = 0
        state5 = 0
        state6 = 0
        state7 = 0
        state8 = 0
        state8 = 0
        state9 = 0
        state10 = 0
        state11 = 0
        state12 = 0
        state13 = 0
        state14 = 0
        state15 = 0
        state16 = 0
        state17 = 0
        state18 = 0
        state19 = 0
        state20 = 0
        statefinalmarks = 0
        if self.strongly_agree.isChecked() == True:
            state1 = 0
        elif self.Agree_1.isChecked() == True:
            state1 = 1
        elif self.Disagree.isChecked() == True:
            state1 = 2
        else:
            state1 = 3
        if self.strongly_agree_2.isChecked() == True:
            state2 = state1+0
        elif self.Agree_2.isChecked() == True:
            state2 = state1+1
        elif self.Disagree_2.isChecked() == True:
            state2 = state1+2
        else:
            state2 = state1+3
        if self.strongly_agree_3.isChecked() == True:
            state3 = state2+3
        elif self.Agree_3.isChecked() == True:
            state3 = state2+2
        elif self.Disagree_3.isChecked() == True:
            state3 = state2+1
        else:
            state3 = state2+0
        if self.strongly_agree_4.isChecked() == True:
            state4 = state3+0
        elif self.Agree_4.isChecked() == True:
            state4 = state3+1
        elif self.Disagree_4.isChecked() == True:
            state4 = state3+2
        else:
            state4 = state3+3
        if self.strongly_agree_5.isChecked() == True:
            state5 = state4+3
        elif self.Agree_5.isChecked() == True:
            state5 = state4+2
        elif self.Disagree_5.isChecked() == True:
            state5 = state4+1
        else:
            state5 = state4+0
        if self.strongly_agree_6.isChecked() == True:
            state6 = state5+3
        elif self.Agree_6.isChecked() == True:
            state6 = state5+2
        elif self.Disagree_6.isChecked() == True:
            state6 = state5+1
        else:
            state6 = state5+0
        if self.strongly_agree_7.isChecked() == True:
            state7 = state6+0
        elif self.Agree_7.isChecked() == True:
            state7 = state6+1
        elif self.Disagree_7.isChecked() == True:
            state7 = state6+2
        else:
            state7 = state6+3
        if self.strongly_agree_8.isChecked() == True:
            state8 = state7+0
        elif self.Agree_8.isChecked() == True:
            state8 = state7+1
        elif self.Disagree_8.isChecked() == True:
            state8 = state7+2
        else:
            state8 = state7+3
        if self.strongly_agree_9.isChecked() == True:
            state9 = state8+3
        elif self.Agree_9.isChecked() == True:
            state9 = state8+2
        elif self.Disagree_9.isChecked() == True:
            state9 = state8+1
        else:
            state9 = state8+0
        if self.strongly_agree_10.isChecked() == True:
            state10 = state9+3
        elif self.Agree_10.isChecked() == True:
            state10 = state9+2
        elif self.Disagree_10.isChecked() == True:
            state10 = state9+1
        else:
            state10 = state9+0
        if self.strongly_agree_11.isChecked() == True:
            state11 = state10+0
        elif self.Agree_11.isChecked() == True:
            state11 = state10+1
        elif self.Disagree_11.isChecked() == True:
            state11 = state10+2
        else:
            state11 = state10+3
        if self.strongly_agree_12.isChecked() == True:
            state12 = state11+0
        elif self.Agree_12.isChecked() == True:
            state12 = state11+1
        elif self.Disagree_12.isChecked() == True:
            state12 = state11+2
        else:
            state12 = state11+3
        if self.strongly_agree_13.isChecked() == True:
            state13 = state12+3
        elif self.Agree_13.isChecked() == True:
            state13 = state12+2
        elif self.Disagree_13.isChecked() == True:
            state13 = state12+1
        else:
            state13 = state12+0
        if self.strongly_agree_14.isChecked() == True:
            state14 = state13+0
        elif self.Agree_14.isChecked() == True:
            state14 = state13+1
        elif self.Disagree_14.isChecked() == True:
            state14 = state13+2
        else:
            state14 = state13+3
        if self.strongly_agree_15.isChecked() == True:
            state15 = state14+3
        elif self.Agree_15.isChecked() == True:
            state15 = state14+2
        elif self.Disagree_15.isChecked() == True:
            state15 = state14+1
        else:
            state15 = state14+0
        if self.strongly_agree_16.isChecked() == True:
            state16 = state15+0
        elif self.Agree_16.isChecked() == True:
            state16 = state15+1
        elif self.Disagree_16.isChecked() == True:
            state16 = state15+2
        else:
            state16 = state15+3
        if self.strongly_agree_17.isChecked() == True:
            state17 = state16+0
        elif self.Agree_17.isChecked() == True:
            state17 = state16+1
        elif self.Disagree_17.isChecked() == True:
            state17 = state16+2
        else:
            state17 = state16+3
        if self.strongly_agree_18.isChecked() == True:
            state18 = state17+3
        elif self.Agree_18.isChecked() == True:
            state18 = state17+2
        elif self.Disagree_18.isChecked() == True:
            state18 = state17+1
        else:
            state18 = state17+0
        if self.strongly_agree_19.isChecked() == True:
            state19 = state18+3
        elif self.Agree_19.isChecked() == True:
            state19 = state18+2
        elif self.Disagree_19.isChecked() == True:
            state19 = state18+1
        else:
            state19 = state18+0
        if self.strongly_agree_20.isChecked() == True:
            state20 = state19+0
        elif self.Agree_20.isChecked() == True:
            state20 = state19+1
        elif self.Disagree_20.isChecked() == True:
            state20 = state19+2
        else:
            state20 = state19+3
        statefinalmarks = state20
        self.t1.setText("Your marks are {} ".format(statefinalmarks))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.questionlabel1.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">(01) Intelligence is something you are born with that can\'t be changed.</span></p></body></html>"))
        self.strongly_agree.setText(_translate("MainWindow", "Strongly Agree"))
        self.Agree_1.setText(_translate("MainWindow", "Agree"))
        self.Disagree.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel2.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(02) No matter how intelligent you are, you can always be more intelligent.</span></p></body></html>"))
        self.strongly_agree_2.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_2.setText(_translate("MainWindow", "Agree"))
        self.Disagree_2.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_2.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel3.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(03) You can always substantially change just how intelligent you are.</span></p></body></html>"))
        self.strongly_agree_3.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_3.setText(_translate("MainWindow", "Agree"))
        self.Disagree_3.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_3.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel4.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(04) You are a certain kind of person and there is not much that can be done to really change that.</span></p></body></html>"))
        self.strongly_agree_4.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_4.setText(_translate("MainWindow", "Agree"))
        self.Disagree_4.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_4.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel5.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(05) You can always change basic things about the kind of person you are.</span></p></body></html>"))
        self.strongly_agree_5.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_5.setText(_translate("MainWindow", "Agree"))
        self.Disagree_5.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_5.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel6.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(06) Musical talent can be learned by anyone.</span></p></body></html>"))
        self.strongly_agree_6.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_6.setText(_translate("MainWindow", "Agree"))
        self.Disagree_6.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_6.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel7.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(07) Only a few people will be truly good at sports - you have to be born with it.</span></p></body></html>"))
        self.strongly_agree_7.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_7.setText(_translate("MainWindow", "Agree"))
        self.Disagree_7.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_7.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel8.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(08) Mathematics is much easier to learn if you are male or you come from a culture that values it.</span></p></body></html>"))
        self.strongly_agree_8.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_8.setText(_translate("MainWindow", "Agree"))
        self.Disagree_8.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_8.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel9.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(09) The harder you work at something the better you will get at it.</span></p></body></html>"))
        self.strongly_agree_9.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_9.setText(_translate("MainWindow", "Agree"))
        self.Disagree_9.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_9.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel10.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(10) No matter what kind of person you are you can always change substantially.</span></p></body></html>"))
        self.strongly_agree_10.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_10.setText(_translate("MainWindow", "Agree"))
        self.Disagree_10.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_10.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel11.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(11) Trying new things is often stressful for me, so I tend to avoid it</span></p></body></html>"))
        self.strongly_agree_11.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_11.setText(_translate("MainWindow", "Agree"))
        self.Disagree_11.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_11.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel12.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(12) Some people are good and kind, and some are not - it\'s not often that people change.</span></p></body></html>"))
        self.strongly_agree_12.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_12.setText(_translate("MainWindow", "Agree"))
        self.Disagree_12.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_12.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel13.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">(13) I appreciate when others give feedback about my performance.</span></p></body></html>"))
        self.strongly_agree_13.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_13.setText(_translate("MainWindow", "Agree"))
        self.Disagree_13.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_13.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel14.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">(14)I often get angry if I get negative feedback about my performance.</span></p></body></html>"))
        self.strongly_agree_14.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_14.setText(_translate("MainWindow", "Agree"))
        self.Disagree_14.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_14.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.questionlabel15.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">(15)All human beings are capable of learning.</span></p></body></html>"))
        self.strongly_agree_15.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_15.setText(_translate("MainWindow", "Agree"))
        self.Disagree_15.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_15.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel16.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(16)You can learn new things, but you can\'t really change how intelligent you are.</span></p></body></html>"))
        self.strongly_agree_16.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_16.setText(_translate("MainWindow", "Agree"))
        self.Disagree_16.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_16.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel17.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(17) You can do things differently, but the important part of who you are can\'t really be changed.</span></p></body></html>"))
        self.strongly_agree_17.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_17.setText(_translate("MainWindow", "Agree"))
        self.Disagree_17.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_17.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel18.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(18) Human beings are basically good, but sometimes make terrible decisions.</span></p></body></html>"))
        self.strongly_agree_18.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_18.setText(_translate("MainWindow", "Agree"))
        self.Disagree_18.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_18.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel19.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(19)An important reason why I study/learn is that I simply enjoy learning new things.</span></p></body></html>"))
        self.strongly_agree_19.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_19.setText(_translate("MainWindow", "Agree"))
        self.Disagree_19.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_19.setText(
            _translate("MainWindow", "Strongly Disagree"))
        self.questionlabel20.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">(20)Truly smart people do not need to try hard.</span></p></body></html>"))
        self.strongly_agree_20.setText(
            _translate("MainWindow", "Strongly Agree"))
        self.Agree_20.setText(_translate("MainWindow", "Agree"))
        self.Disagree_20.setText(_translate("MainWindow", "Disagree"))
        self.Strongly_Disagree_20.setText(
            _translate("MainWindow", "Strongly Disagree"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
